using System;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

namespace QueueFightGame.UI
{
    public partial class MainMenuForm : Form
    {
        private Button playButton;

        public MainMenuForm()
        {
            InitializeComponent(); // This loads controls from Designer.cs
            SetupCustomComponents();
        }


        // If not using the Designer, you initialize controls here
        private void SetupCustomComponents()
        {
            this.Text = "Queue Fight Game - Главное Меню";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.ClientSize = new Size(800, 600); // Example size

            BackgroundImage = Image.FromFile("Resources/zastavka.png");
            BackgroundImageLayout = ImageLayout.Stretch;

            // Background Image (Set this in the Form's BackgroundImage property in the Designer ideally)
            // Or load programmatically:
            try
            {
                // Ensure the image is in the executable directory or provide full path
                // Set Build Action to "Content" and Copy to Output Directory to "Copy if newer" for the image file
                // this.BackgroundImage = Image.FromFile("Resources/main_background.jpg"); // Adjust path
                this.BackgroundImageLayout = ImageLayout.Stretch;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Не удалось загрузить фон: {ex.Message}");
            }

            var loadButton = new Button
            {
                Text = "Загрузить игру",
                Size = new Size(180, 60),
                Location = new Point((ClientSize.Width - 180) / 2, (ClientSize.Height - 60) / 2 + 100),
                Font = new Font("Segoe UI", 12f, FontStyle.Bold)
            };
            loadButton.Click += (s, e) => {
                using (var dlg = new OpenFileDialog { Filter = "JSON|*.json" })
                    if (dlg.ShowDialog() == DialogResult.OK)
                    {
                        var mgr = new GameManager(new MemoryLogger());
                        mgr.LoadState(dlg.FileName);
                        var bf = new BattleForm(mgr);
                        bf.Show();
                        this.Hide();
                        bf.FormClosed += (s2, e2) => this.Close();


                    }
            };

            this.Controls.Add(loadButton);


            playButton = new Button
            {
                Size = new Size(200, 80),
                BackgroundImage = Image.FromFile("Resources/knopkaplay.png"),
                BackgroundImageLayout = ImageLayout.Stretch,
                FlatStyle = FlatStyle.Flat,
                BackColor = Color.Transparent,
                FlatAppearance =
        {
            BorderSize   = 0,
            MouseDownBackColor = Color.Transparent,
            MouseOverBackColor = Color.Transparent
        }
            };
            playButton.Location = new Point((ClientSize.Width - playButton.Width) / 2,
                                             (ClientSize.Height - playButton.Height) / 2);

            playButton.Click += PlayButton_Click;

            this.Controls.Add(playButton);
        }

        private void PlayButton_Click(object sender, EventArgs e)
        {
            // Open the game setup form
            GameSetupForm setupForm = new GameSetupForm();
            setupForm.Show();
            this.Hide(); // Hide main menu instead of closing, so app doesn't exit

            // Ensure the application exits when the setup form (and subsequent forms) are closed
            setupForm.FormClosed += (s, args) => this.Close();
        }

        // This method is generated by the designer - keep it if using the designer
        // Or remove if creating controls manually in code
        private void InitializeComponent()
        {
            // Component initialization code (usually in Designer.cs)
            this.SuspendLayout();
            //
            // MainMenuForm
            //
            this.Name = "MainMenuForm";
            this.ResumeLayout(false);
        }
    }
}